name: Application CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths:
      - 'AWSCloud/01-serverless-web-app/app/**'

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: pip install -r ./AWSCloud/01-serverless-web-app/app/lambda_function/requirements.txt -t ./package
        working-directory: ./AWSCloud/01-serverless-web-app/app/lambda_function

      - name: Zip Lambda function code
        run: |
          cd ./AWSCloud/01-serverless-web-app/app/lambda_function/package
          zip -r9 ../function.zip .
          cd ../
          zip -g function.zip main.py

      - name: Deploy Lambda function
        run: aws lambda update-function-code --function-name YOUR_LAMBDA_FUNCTION_NAME --zip-file fileb://function.zip
        working-directory: ./AWSCloud/01-serverless-web-app/app/lambda_function

  deploy-website:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Sync S3 bucket
        run: aws s3 sync ./AWSCloud/01-serverless-web-app/app/website/ s3://YOUR_S3_BUCKET_NAME --delete


